services:
  - type: web
    name: shopzen-api
    runtime: docker
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Jwt__Secret
        sync: false
      - key: Stripe__SecretKey
        sync: false
      - key: Stripe__WebhookSecret
        sync: false
